### ISSUE TITLE
Implement queryPurchases

### ISSUE THREAD

**Issue by josh-burton** [bufferapp/ReactivePlayBilling#2]
This library currently only implements `queryPurchaseHistoryAsync()` which returns all purchases, even refunded ones.

`queryPurchases()` returns only the uses current purchases (I think).

**Comment by josh-burton** [comment]
I would make a PR for this but the latest snapshot seems ahead of this repo.

**Comment by hitherejoe** [comment]
Looks like this has been added now :)
