### ISSUE TITLE
Advise on retry policies is much appreciated.

### ISSUE THREAD

**Issue by knuttyse** [bufferapp/ReactivePlayBilling#6]
Hi! I am exited about using ReactivePlayBilling in my app, but I am quite new to RxJava.
I wonder if it is necessary to have a retry policy as Google advises. For my onBillingServiceDisconnected() in my app I am considering emitting a Throwable in onError() instead of onNext():

    open fun connect(): Observable<ConnectionResult> {
        return Observable.create {
            billingClient.startConnection(object : BillingClientStateListener {
                override fun onBillingSetupFinished(@BillingClient.BillingResponse
                                                    responseCode: Int) {
                    if (responseCode == BillingClient.BillingResponse.OK) {
                        it.onNext(ConnectionResult.ConnectionSuccess(responseCode))
                    } else {
                        it.onNext(ConnectionResult.ConnectionFailure(responseCode))
                    }
                }

                override fun onBillingServiceDisconnected() {
                    // What if I change to emitting an error?
                    it.onError(Throwable("Google Play Billing - connection closed."))
                    //it.onNext(ConnectionResult.ConnectionFailure())
                }
            })
        }
    }

Then I can chain on a retry/retryWhen, hoping to re-establish the connection. Is this a reasonable approach or am I missing something?

I am a bit worried about getting this error:
https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponse.html#SERVICE_DISCONNECTED
 Google says "Play Store service is not connected now - potentially transient state."  I don't know if it means that the connection will re-appear and thus the stream should not be closed.

**Comment by dima-ostapovets** [comment]
@knuttyse You can convert ConnectionFailure event to Exception and then apply your retry policy:

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        ReactivePlayBilling(this)
                .connect()
                .flatMap {
                    if (isDisconnectEvent(it)) {
                        return@flatMap Observable.error<ConnectionResult>(DisconnectedException())
                    }
                    return@flatMap Observable.just(it)
                }
                .retry(5)//or your retry policy
                .subscribe({}, {})
    }

    private fun isDisconnectEvent(connectionResult: ConnectionResult): Boolean {
        return connectionResult is ConnectionResult.ConnectionFailure
                && connectionResult.result == BillingClient.BillingResponse.SERVICE_DISCONNECTED
    }
```

**Comment by knuttyse** [comment]
Ok! Thank you!
